/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package concurrent_audits;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertTrue(true, "Better not fail");
    }
}
